title: Resume
#url: "https://www.zhihu.com/people/mai-zi-31-63/activities"
#baseurl: "/Zhengcong Fei(费政聪)"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

#sass:
#    style: compressed
#    sass_dir: _sass

#nav:
# - name: "About"
#   link: "index"
# - name: "Resume"
#   link: "resume.pdf"
# - name: "Contact Me"
#   link: "contact"
